apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users # The same as in Deployment
  type: LoadBalancer # ClusterIP for internal communication
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
