apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: andriizilnyk/kub-data-demo:1
          volumeMounts:
            - mountPath: /app/story # /app - WORKDIR, story - folder where data placed
              name: story-volume
      volumes:
        - name: story-volume
          emptyDir: {}

