apiVersion: v1
kind: Service
metadata:
  name: story-service # name to expose
spec:
  selector:
    app: story
  type: LoadBalancer
  ports:
    - port: 80
      protocol: 'TCP'
      targetPort: 3000 # Inside container
