apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv # the same as in host-pv.yaml
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
