apiVersion: v1
kind: Service
metadata:
  name: story-service # name to expose
spec:
  selector:
    app: story
  type: LoadBalancer
#  externalIPs:
#    - 80.11.12.10
  ports:
    - port: 80
      protocol: 'TCP'
      targetPort: 3000 # Inside container
