apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # The PORT inside a Docker container
#    - protocol: TCP
#      port: 443
#      targetPort: 443 # The PORT inside a Docker container
  type: LoadBalancer # NodePort, LoadBalancer, ClusterIP
